# Generated by Django 5.1.6 on 2026-01-04 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ano', models.PositiveIntegerField()),
                ('quilometragem', models.PositiveIntegerField(help_text='Em km')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('combustivel', models.CharField(choices=[('gasolina', 'Gasolina'), ('diesel', 'Diesel'), ('hibrido', 'Híbrido'), ('eletrico', 'Elétrico'), ('gpl', 'GPL'), ('outro', 'Outro')], default='gasolina', max_length=20)),
                ('transmissao', models.CharField(choices=[('manual', 'Manual'), ('automatica', 'Automática')], default='manual', max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ImagemCarro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='carros/')),
                ('destaque', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='carros.carro')),
            ],
        ),
        migrations.AddField(
            model_name='carro',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carros', to='carros.marca'),
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='carros.marca')),
            ],
            options={
                'ordering': ['nome'],
                'unique_together': {('marca', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='carro',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carros', to='carros.modelo'),
        ),
    ]
