# Generated by Django 5.1.6 on 2026-01-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='tipo_veiculo',
            field=models.CharField(choices=[('auto', 'Automóveis'), ('comercial', 'Comerciais'), ('classico', 'Clássicos')], default='auto', max_length=20),
        ),
    ]
